import pandas as pd

ecom = pd.read_csv('Ecommerce Purchases')
print(ecom.head())
print(ecom.shape)
print(ecom.info())
print()
print("Purchase Average")
print(ecom['Purchase Price'].mean())
print("Purchase Max")
print(ecom['Purchase Price'].max())
print("Purchase Min")
print(ecom['Purchase Price'].min())
print()
print("Accounts with Language 'en'")
print(ecom['Language'].value_counts()['en'])
print("Job Title 'Lawyer'")
print(ecom['Job'].value_counts()['Lawyer'])
print(ecom['AM or PM'].value_counts())
print("Purchase Price from Lot '90 WT'")
print(ecom[ecom['Lot'] == '90 WT']['Purchase Price'])
print("Number of people with AmEx card and Purchase > 95")
print(ecom[(ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95)].shape[0])
print()
print("Number of CC expiring in 2025")
print(ecom['CC Exp Date'].apply(lambda x: '/25' in x).sum())
print("Top 5 most common email providers")
print(ecom['Email'].apply(lambda x: x.split('@')[1]).value_counts().head(5))