import pandas as pd

sal = pd.read_csv('Salaries.csv')
print(sal.head())
print(sal.info())
print()
print("Average BasePay")
print(round(sal['BasePay'].mean(), 2))
print("Highest OvertimePay")
print(sal['OvertimePay'].max())
print()
print("Job Title for Joseph Driscoll")
print(sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle'])
print("Joseph Driscoll's Total Pay")
print(sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits'])
print()
print("Highest Paid Person")
print(sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()][['EmployeeName', 'TotalPayBenefits']])
print("Lowest Paid Person")
print(sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()][['EmployeeName', 'TotalPayBenefits']])
print("Average Base Pay per year")
print(sal.groupby('Year')['BasePay'].mean())
print()
print("Unique Job Titles")
print(sal['JobTitle'].nunique())
print("Top 5 Most Common Jobs")
print(sal['JobTitle'].value_counts().head(5))
print("Unique 2013 Job Titles")
print(sal[sal['Year'] == 2013]['JobTitle'].nunique())
print()
print("Number of People with Job Titles Including 'Chief'")
print(sal['JobTitle'].apply(lambda x: 'chief' in x.lower().split()).sum())